/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service Info */
        get: operations["service_info_api_v1_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capability Catalog */
        get: operations["capability_catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Project */
        get: operations["open_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/authoring/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Authoring Turn */
        post: operations["create_authoring_turn_api_v1_projects__project_id__authoring_turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/authoring/turns/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Authoring Turn */
        post: operations["stream_authoring_turn_api_v1_projects__project_id__authoring_turns_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/blueprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Blueprint */
        put: operations["save_blueprint_api_v1_projects__project_id__blueprint_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/export/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write Export */
        post: operations["write_export_api_v1_projects__project_id__export_directory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/export/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Export */
        post: operations["preview_export_api_v1_projects__project_id__export_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/export/zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download Export */
        post: operations["download_export_api_v1_projects__project_id__export_zip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Layout */
        get: operations["load_layout_api_v1_projects__project_id__layout_get"];
        /** Save Layout */
        put: operations["save_layout_api_v1_projects__project_id__layout_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_api_v1_projects__project_id__proposals_get"];
        put?: never;
        /** Create Proposal */
        post: operations["create_proposal_api_v1_projects__project_id__proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Proposal */
        delete: operations["delete_proposal_api_v1_projects__project_id__proposals__proposal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/proposals/{proposal_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Proposal */
        post: operations["accept_proposal_api_v1_projects__project_id__proposals__proposal_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Proposal */
        post: operations["reject_proposal_api_v1_projects__project_id__proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Project */
        post: operations["validate_project_api_v1_projects__project_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Blueprint Schema */
        get: operations["blueprint_schema_api_v1_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Support Turn */
        post: operations["create_support_turn_api_v1_support_turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support/turns/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream Support Turn */
        post: operations["stream_support_turn_api_v1_support_turns_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Buffer */
        post: operations["validate_buffer_api_v1_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentCallNodeSpec */
        AgentCallNodeSpec: {
            /** Dependson */
            dependsOn?: string[];
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Phase */
            phase?: string | null;
            /** Prompt */
            prompt: string;
            /** Subagent */
            subagent?: string | null;
            /** Tools */
            tools?: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent_call";
        };
        /** AgentTickRoutineSpec */
        AgentTickRoutineSpec: {
            budget?: components["schemas"]["BudgetSpec"];
            /** Charter */
            charter: string;
            /** Displayname */
            displayName: string;
            /** Donewhen */
            doneWhen?: (components["schemas"]["TextContainsVerifierSpec"] | components["schemas"]["JsonSchemaVerifierSpec"] | components["schemas"]["CustomTodoVerifierSpec"]) | null;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "agent_tick";
            /** Maxturns */
            maxTurns?: number | null;
            /** Prompt */
            prompt: string;
            /**
             * Target
             * @default runtime_agent
             * @constant
             */
            target: "runtime_agent";
            /** Triggers */
            triggers?: string[];
            /** Verify */
            verify?: (components["schemas"]["TextContainsVerifierSpec"] | components["schemas"]["JsonSchemaVerifierSpec"] | components["schemas"]["CustomTodoVerifierSpec"]) | null;
        };
        /** BashPermissionRuleSpec */
        BashPermissionRuleSpec: {
            /**
             * Decision
             * @default ask
             * @enum {string}
             */
            decision: "allow" | "deny" | "ask" | "passthrough";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "bash";
            /** Patterns */
            patterns: string[];
        };
        /** Blueprint */
        Blueprint: {
            /**
             * Apiversion
             * @constant
             */
            apiVersion: "studio.linch.dev/v1alpha2";
            /**
             * Kind
             * @constant
             */
            kind: "LinchProject";
            metadata: components["schemas"]["ProjectMetadata"];
            spec: components["schemas"]["ProjectSpec"];
        };
        /** BudgetSpec */
        BudgetSpec: {
            /** Maxcostusd */
            maxCostUsd?: number | null;
            /** Maxtokens */
            maxTokens?: number | null;
            /**
             * Warnratio
             * @default 0.9
             */
            warnRatio: number;
        };
        /** CITriggerSpec */
        CITriggerSpec: {
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ci";
            /**
             * Provider
             * @default generic
             * @enum {string}
             */
            provider: "generic" | "github_actions";
        };
        /** CapabilityAreaResponse */
        CapabilityAreaResponse: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Order */
            order: number;
            /** Title */
            title: string;
        };
        /**
         * CapabilityCatalogResponse
         * @description Wire projection of the hand-authored capability catalog.
         *
         *     Mirrors ``CapabilityCatalog.to_dict``; ``test_catalog_response_still_matches_
         *     catalog_document`` fails if the two drift apart.
         */
        CapabilityCatalogResponse: {
            /** Areas */
            areas: components["schemas"]["CapabilityAreaResponse"][];
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityRecordResponse"][];
            catalogVersion: components["schemas"]["CatalogVersionResponse"];
            relationMatrix: components["schemas"]["EditableRelationMatrixResponse"];
            /** Statuses */
            statuses: components["schemas"]["CapabilityStatusResponse"][];
        };
        /** CapabilityRecordResponse */
        CapabilityRecordResponse: {
            /** Area */
            area: string;
            /** Badge */
            badge: string;
            /** Executionmodel */
            executionModel: boolean;
            /** Exportallowed */
            exportAllowed: boolean;
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "runtime_ready" | "skeleton_todo" | "unsupported";
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** CapabilitySelection */
        CapabilitySelection: {
            compaction?: components["schemas"]["CompactionCapabilitySpec"];
            context?: components["schemas"]["ContextCapabilitySpec"];
            evals?: components["schemas"]["EvalsCapabilitySpec"];
            extensions?: components["schemas"]["ExtensionsCapabilitySpec"];
            externalDatabase?: components["schemas"]["ExternalDatabaseCapabilitySpec"];
            filesystem?: components["schemas"]["FilesystemCapabilitySpec"];
            hooks?: components["schemas"]["HooksCapabilitySpec"];
            memory?: components["schemas"]["MemoryCapabilitySpec"];
            observation?: components["schemas"]["ObservationCapabilitySpec"];
            permissions?: components["schemas"]["PermissionsCapabilitySpec"];
            persistence?: components["schemas"]["PersistenceCapabilitySpec"];
            prompt?: components["schemas"]["PromptCapabilitySpec"];
            reliability?: components["schemas"]["ReliabilityCapabilitySpec"];
            structuredOutput?: components["schemas"]["StructuredOutputCapabilitySpec"];
        };
        /** CapabilityStatusResponse */
        CapabilityStatusResponse: {
            /** Badge */
            badge: string;
            /** Description */
            description: string;
            /** Exportallowed */
            exportAllowed: boolean;
            /**
             * Id
             * @enum {string}
             */
            id: "runtime_ready" | "skeleton_todo" | "unsupported";
            /** Order */
            order: number;
        };
        /** CatalogVersionResponse */
        CatalogVersionResponse: {
            /** Apiversion */
            apiVersion: string;
            /** Revision */
            revision: number;
            /**
             * Source
             * @constant
             */
            source: "hand_authored";
            /** Targetlinch */
            targetLinch: string;
        };
        /** ClassToolSpec */
        ClassToolSpec: {
            /** Description */
            description: string;
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /** Inputschema */
            inputSchema?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "class";
            /**
             * Parallel
             * @default true
             */
            parallel: boolean;
            /** Resources */
            resources?: components["schemas"]["ResourceSpec"][];
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /**
             * Scope
             * @default read
             * @enum {string}
             */
            scope: "read" | "write" | "exec";
            /** Timeoutms */
            timeoutMs?: number | null;
        };
        /** CompactionCapabilitySpec */
        CompactionCapabilitySpec: {
            /**
             * Keeprecentturns
             * @default 10
             */
            keepRecentTurns: number;
            ladder?: components["schemas"]["CompactionLadderSpec"];
            /**
             * Maxoutputtokens
             * @default 8192
             */
            maxOutputTokens: number;
            /**
             * Strategy
             * @default none
             * @enum {string}
             */
            strategy: "none" | "default_coding" | "general" | "detailed" | "custom";
        };
        /** CompactionLadderSpec */
        CompactionLadderSpec: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Keeprecentturns
             * @default 10
             */
            keepRecentTurns: number;
            /**
             * Maxforcedcompactions
             * @default 3
             */
            maxForcedCompactions: number;
            /**
             * Micro
             * @default true
             */
            micro: boolean;
            /**
             * Resetreadtracker
             * @default true
             */
            resetReadTracker: boolean;
        };
        /** CompletionSpec */
        CompletionSpec: {
            /**
             * Maxretries
             * @default 2
             */
            maxRetries: number;
            /**
             * Mode
             * @default agent_judged
             * @enum {string}
             */
            mode: "agent_judged" | "verifier_gated";
            /** Verifiers */
            verifiers?: (components["schemas"]["TextContainsVerifierSpec"] | components["schemas"]["JsonSchemaVerifierSpec"] | components["schemas"]["CustomTodoVerifierSpec"])[];
        };
        /** ContextCapabilitySpec */
        ContextCapabilitySpec: {
            /**
             * Custombuilder
             * @default false
             */
            customBuilder: boolean;
            /**
             * Dynamictoolselector
             * @default false
             */
            dynamicToolSelector: boolean;
            /**
             * Maxitems
             * @default 5
             */
            maxItems: number;
            /** Maxtokens */
            maxTokens?: number | null;
            /**
             * Memoryrecall
             * @default false
             */
            memoryRecall: boolean;
        };
        /** CronTriggerSpec */
        CronTriggerSpec: {
            /** Cron */
            cron: string;
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "cron";
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** CustomTodoVerifierSpec */
        CustomTodoVerifierSpec: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "custom_todo";
        };
        /** DatabaseToolSpec */
        DatabaseToolSpec: {
            /** Description */
            description: string;
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /** Idempotencyargument */
            idempotencyArgument?: string | null;
            /** Inputschema */
            inputSchema?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "database";
            /**
             * Operation
             * @default read
             * @enum {string}
             */
            operation: "read" | "write";
            /**
             * Parallel
             * @default true
             */
            parallel: boolean;
            /** Resources */
            resources?: components["schemas"]["ResourceSpec"][];
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /**
             * Scope
             * @default read
             * @enum {string}
             */
            scope: "read" | "write" | "exec";
            /** Timeoutms */
            timeoutMs?: number | null;
        };
        /**
         * Diagnostic
         * @description A machine-stable validation finding safe to return through the API.
         */
        Diagnostic: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
            /** Remediation */
            remediation: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
        };
        /**
         * DirectToolNodeSpec
         * @description Parsed only so validation can return an explicit unsupported diagnostic.
         */
        DirectToolNodeSpec: {
            /** Dependson */
            dependsOn?: string[];
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Tool */
            tool: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "direct_tool";
        };
        /** DirectoryExportRequest */
        DirectoryExportRequest: {
            /** Target */
            target: string;
        };
        /** DirectoryExportResponse */
        DirectoryExportResponse: {
            /** Blueprintdigest */
            blueprintDigest: string;
            /** Target */
            target: string;
        };
        /** EditableRelationMatrixResponse */
        EditableRelationMatrixResponse: {
            /** Relations */
            relations: components["schemas"]["EditableRelationResponse"][];
            version: components["schemas"]["RelationMatrixVersionResponse"];
        };
        /** EditableRelationResponse */
        EditableRelationResponse: {
            /** Constraints */
            constraints: string[];
            /**
             * Decision
             * @enum {string}
             */
            decision: "allow" | "deny";
            /** Field */
            field?: string | null;
            /** Id */
            id: string;
            /** Order */
            order: number;
            /** Reason */
            reason: string;
            /** Relation */
            relation: string;
            /** Sourcekind */
            sourceKind: string;
            /** Targetkind */
            targetKind: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Currentdigest */
            currentDigest?: string | null;
            /** Diagnostics */
            diagnostics?: components["schemas"]["Diagnostic"][];
            /** Message */
            message: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** EvalCaseSpec */
        EvalCaseSpec: {
            /** Expectedcontains */
            expectedContains?: string | null;
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
        };
        /** EvalsCapabilitySpec */
        EvalsCapabilitySpec: {
            /** Cases */
            cases?: components["schemas"]["EvalCaseSpec"][];
            /**
             * Domainscorerskeleton
             * @default false
             */
            domainScorerSkeleton: boolean;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /** ExportPreviewResponse */
        ExportPreviewResponse: {
            /** Blueprintdigest */
            blueprintDigest: string;
            /** Files */
            files: components["schemas"]["GeneratedFilePreview"][];
        };
        /** ExtensionsCapabilitySpec */
        ExtensionsCapabilitySpec: {
            /**
             * Isolationadapter
             * @default none
             * @enum {string}
             */
            isolationAdapter: "none" | "tempdir" | "external";
            /**
             * Livemcpdiscovery
             * @default false
             */
            liveMcpDiscovery: boolean;
            /**
             * Mailboxadapter
             * @default none
             * @enum {string}
             */
            mailboxAdapter: "none" | "in_memory" | "sqlite" | "external";
            /** Mcpservers */
            mcpServers?: (components["schemas"]["McpStdioSpec"] | components["schemas"]["McpHttpSpec"])[];
            /**
             * Schedulestoreadapter
             * @default none
             * @enum {string}
             */
            scheduleStoreAdapter: "none" | "in_memory" | "sqlite" | "external";
        };
        /** ExternalDatabaseCapabilitySpec */
        ExternalDatabaseCapabilitySpec: {
            /** Adaptertemplates */
            adapterTemplates?: ("memory_store" | "file_backend" | "schedule_store" | "mailbox" | "session_store" | "run_store")[];
            /** Dsnenv */
            dsnEnv?: string | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Vectorguidance */
            vectorGuidance?: ("faiss" | "pgvector" | "qdrant")[];
        };
        /** FilesystemCapabilitySpec */
        FilesystemCapabilitySpec: {
            /**
             * Backend
             * @default none
             * @enum {string}
             */
            backend: "none" | "state" | "disk" | "sqlite" | "composite" | "external";
            /**
             * Offloadenabled
             * @default false
             */
            offloadEnabled: boolean;
            /**
             * Offloadthresholdfraction
             * @default 0.1
             */
            offloadThresholdFraction: number;
            /** Offloadthresholdtokens */
            offloadThresholdTokens?: number | null;
            /**
             * Previewlines
             * @default 10
             */
            previewLines: number;
            /**
             * Root
             * @default .linch/files
             */
            root: string;
        };
        /** FunctionToolSpec */
        FunctionToolSpec: {
            /** Description */
            description: string;
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /** Inputschema */
            inputSchema?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "function";
            /**
             * Parallel
             * @default true
             */
            parallel: boolean;
            /** Resources */
            resources?: components["schemas"]["ResourceSpec"][];
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
            /**
             * Scope
             * @default read
             * @enum {string}
             */
            scope: "read" | "write" | "exec";
            /** Timeoutms */
            timeoutMs?: number | null;
        };
        /** GeneratedFilePreview */
        GeneratedFilePreview: {
            /** Capabilityid */
            capabilityId: string;
            /** Content */
            content: string;
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /** HooksCapabilitySpec */
        HooksCapabilitySpec: {
            /**
             * Custommiddleware
             * @default false
             */
            customMiddleware: boolean;
            /**
             * Readbeforewrite
             * @default true
             */
            readBeforeWrite: boolean;
            /** Redactionrules */
            redactionRules?: components["schemas"]["RedactionRuleSpec"][];
            /**
             * Stoppredicateskeleton
             * @default false
             */
            stopPredicateSkeleton: boolean;
            /**
             * Toolcache
             * @default false
             */
            toolCache: boolean;
        };
        /** JsonSchemaVerifierSpec */
        JsonSchemaVerifierSpec: {
            /** Feedback */
            feedback?: string | null;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "json_schema";
            /** Schema */
            schema: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        JsonValue: unknown;
        /** LayoutDocument */
        LayoutDocument: {
            /** Nodes */
            nodes?: components["schemas"]["LayoutNode"][];
            viewport?: components["schemas"]["LayoutViewport"];
        };
        /** LayoutNode */
        LayoutNode: {
            /** Height */
            height?: number | null;
            /** Id */
            id: string;
            /** Width */
            width?: number | null;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** LayoutResponse */
        LayoutResponse: {
            /** Id */
            id: string;
            layout: components["schemas"]["LayoutDocument"];
        };
        /** LayoutViewport */
        LayoutViewport: {
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * Zoom
             * @default 1
             */
            zoom: number;
        };
        /** LoopGuardSpec */
        LoopGuardSpec: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Forcefinalanswer
             * @default false
             */
            forceFinalAnswer: boolean;
            /**
             * Maxconsecutivefailures
             * @default 3
             */
            maxConsecutiveFailures: number;
            /**
             * Maxidenticaltoolcalls
             * @default 3
             */
            maxIdenticalToolCalls: number;
        };
        /** ManualTriggerSpec */
        ManualTriggerSpec: {
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "manual";
        };
        /** McpHttpSpec */
        McpHttpSpec: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "http";
            /** Tokenenv */
            tokenEnv?: string | null;
            /** Url */
            url: string;
        };
        /** McpStdioSpec */
        McpStdioSpec: {
            /** Args */
            args?: string[];
            /** Command */
            command: string;
            /** Env */
            env?: {
                [key: string]: string;
            };
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "stdio";
        };
        /** MemoryCapabilitySpec */
        MemoryCapabilitySpec: {
            /**
             * Backend
             * @default none
             * @enum {string}
             */
            backend: "none" | "in_memory" | "sqlite" | "postgres_keyword" | "tiered" | "faiss" | "pgvector" | "qdrant" | "custom";
            /** Dsnenv */
            dsnEnv?: string | null;
            /**
             * Extractionhook
             * @default false
             */
            extractionHook: boolean;
            /** Namespace */
            namespace?: string | null;
            /**
             * Searchtool
             * @default false
             */
            searchTool: boolean;
            /**
             * Upserttool
             * @default false
             */
            upsertTool: boolean;
        };
        /** MigrationWarningResponse */
        MigrationWarningResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
            /** Remediation */
            remediation: string;
            /**
             * Requiresconfirmation
             * @default true
             */
            requiresConfirmation: boolean;
        };
        /** ObservationCapabilitySpec */
        ObservationCapabilitySpec: {
            /**
             * Logging
             * @default true
             */
            logging: boolean;
            /**
             * Otel
             * @default false
             */
            otel: boolean;
            /**
             * Runreport
             * @default true
             */
            runReport: boolean;
            /** Vendorexporter */
            vendorExporter?: string | null;
        };
        /** PathPermissionRuleSpec */
        PathPermissionRuleSpec: {
            /**
             * Decision
             * @default ask
             * @enum {string}
             */
            decision: "allow" | "deny" | "ask" | "passthrough";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "path";
            /** Paths */
            paths: string[];
            /** Tools */
            tools?: string[];
        };
        /** PermissionsCapabilitySpec */
        PermissionsCapabilitySpec: {
            /**
             * Hitlcallbackskeleton
             * @default false
             */
            hitlCallbackSkeleton: boolean;
            /**
             * Mode
             * @default interactive
             * @enum {string}
             */
            mode: "interactive" | "accept_edits" | "trusted";
            /**
             * Organizationpolicyskeleton
             * @default false
             */
            organizationPolicySkeleton: boolean;
            /** Rules */
            rules?: (components["schemas"]["ToolPermissionRuleSpec"] | components["schemas"]["PathPermissionRuleSpec"] | components["schemas"]["BashPermissionRuleSpec"])[];
        };
        /** PersistenceCapabilitySpec */
        PersistenceCapabilitySpec: {
            /**
             * Durableresume
             * @default false
             */
            durableResume: boolean;
            /**
             * Runstore
             * @default in_memory
             * @enum {string}
             */
            runStore: "in_memory" | "sqlite" | "external";
            /**
             * Sessionstore
             * @default in_memory
             * @enum {string}
             */
            sessionStore: "in_memory" | "sqlite" | "external";
        };
        /** ProjectCreateRequest */
        ProjectCreateRequest: {
            /** Id */
            id: string;
            /**
             * Template
             * @default agent
             * @enum {string}
             */
            template: "agent" | "goal_verified" | "directed_workflow" | "coordinator" | "routine";
            /** Title */
            title?: string | null;
        };
        /** ProjectDocument */
        ProjectDocument: {
            blueprint: components["schemas"]["Blueprint"];
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Digest */
            digest: string;
            /** Exportready */
            exportReady: boolean;
            /** Id */
            id: string;
            layout: components["schemas"]["LayoutDocument"];
            /** Migratedfrom */
            migratedFrom?: string | null;
            /** Migrationwarnings */
            migrationWarnings?: components["schemas"]["MigrationWarningResponse"][];
            /** Yaml */
            yaml: string;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectSummary"][];
        };
        /** ProjectMetadata */
        ProjectMetadata: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /** Title */
            title: string;
        };
        /** ProjectSpec */
        ProjectSpec: {
            capabilities?: components["schemas"]["CapabilitySelection"];
            /** Package */
            package: string;
            /** Routines */
            routines?: (components["schemas"]["AgentTickRoutineSpec"] | components["schemas"]["WorkflowRunRoutineSpec"])[];
            runtime?: components["schemas"]["RuntimeSpec"];
            /** Skills */
            skills?: components["schemas"]["SkillSpec"][];
            /** Subagents */
            subagents?: components["schemas"]["SubagentSpec"][];
            target?: components["schemas"]["TargetSpec"];
            /** Tools */
            tools?: (components["schemas"]["FunctionToolSpec"] | components["schemas"]["ClassToolSpec"] | components["schemas"]["DatabaseToolSpec"])[];
            /** Triggers */
            triggers?: (components["schemas"]["ManualTriggerSpec"] | components["schemas"]["CronTriggerSpec"] | components["schemas"]["CITriggerSpec"] | components["schemas"]["WebhookTriggerSpec"])[];
            /** Workflows */
            workflows?: components["schemas"]["WorkflowSpec"][];
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Digest */
            digest: string;
            /** Exportready */
            exportReady: boolean;
            /** Id */
            id: string;
            /** Model */
            model?: string | null;
            /** Title */
            title: string;
            /** Updatedat */
            updatedAt: string;
        };
        /** PromptCapabilitySpec */
        PromptCapabilitySpec: {
            /**
             * Customdynamicpolicy
             * @default false
             */
            customDynamicPolicy: boolean;
            /**
             * Mode
             * @default append
             * @enum {string}
             */
            mode: "append" | "replace_defaults";
            /** Sections */
            sections?: components["schemas"]["PromptSectionSpec"][];
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** PromptSectionSpec */
        PromptSectionSpec: {
            /**
             * Cacheable
             * @default true
             */
            cacheable: boolean;
            /** Id */
            id: string;
            /**
             * Placement
             * @default before_defaults
             * @enum {string}
             */
            placement: "before_defaults" | "after_defaults" | "after_env";
            /** Text */
            text: string;
        };
        /** ProposalListResponse */
        ProposalListResponse: {
            /** Proposals */
            proposals: components["schemas"]["ProposalResponse"][];
        };
        /** ProposalRequest */
        ProposalRequest: {
            /** Instruction */
            instruction: string;
        };
        /** ProposalResponse */
        ProposalResponse: {
            /** Basedigest */
            baseDigest: string;
            candidate: components["schemas"]["Blueprint"];
            /** Candidatedigest */
            candidateDigest: string;
            /** Createdat */
            createdAt: string;
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Exportready */
            exportReady: boolean;
            /** Id */
            id: string;
            /** Projectid */
            projectId: string;
            /** Semanticdiff */
            semanticDiff: components["schemas"]["SemanticDiffEntry"][];
            /** Summary */
            summary?: string | null;
        };
        /** ProviderSpec */
        ProviderSpec: {
            /** Apikeyenv */
            apiKeyEnv?: string | null;
            /** Baseurlenv */
            baseUrlEnv?: string | null;
            /** Contextwindow */
            contextWindow?: number | null;
            /** Fallbackmodels */
            fallbackModels?: string[];
            /** Kind */
            kind?: ("openai_responses" | "openai_chat" | "anthropic" | "gemini" | "llama_cpp" | "vllm" | "sglang" | "custom") | null;
            /** Location */
            location?: string | null;
            /** Model */
            model?: string | null;
            /** Projectenv */
            projectEnv?: string | null;
            /**
             * Streaming
             * @default true
             */
            streaming: boolean;
            thinking?: components["schemas"]["ThinkingSpec"];
        };
        /** RedactionRuleSpec */
        RedactionRuleSpec: {
            /** Pattern */
            pattern: string;
            /**
             * Replacement
             * @default [REDACTED]
             */
            replacement: string;
        };
        /** RelationMatrixVersionResponse */
        RelationMatrixVersionResponse: {
            /** Apiversion */
            apiVersion: string;
            /** Blueprintapiversion */
            blueprintApiVersion: string;
            /** Revision */
            revision: number;
        };
        /** ReliabilityCapabilitySpec */
        ReliabilityCapabilitySpec: {
            /**
             * Customrecoverypolicy
             * @default false
             */
            customRecoveryPolicy: boolean;
            /**
             * Customtokenestimator
             * @default false
             */
            customTokenEstimator: boolean;
            loopGuard?: components["schemas"]["LoopGuardSpec"];
            /** Maxoutputtokens */
            maxOutputTokens?: number | null;
            /** Maxtoolconcurrency */
            maxToolConcurrency?: number | null;
            providerRetry?: components["schemas"]["RetrySpec"];
            toolRetry?: components["schemas"]["RetrySpec"] | null;
            /** Tooltimeoutms */
            toolTimeoutMs?: number | null;
            truncationRecovery?: components["schemas"]["TruncationRecoverySpec"];
        };
        /** ResourceSpec */
        ResourceSpec: {
            /**
             * Mode
             * @default read
             * @enum {string}
             */
            mode: "read" | "write";
            /** Resource */
            resource: string;
        };
        /** RetrySpec */
        RetrySpec: {
            /**
             * Basedelayms
             * @default 1000
             */
            baseDelayMs: number;
            /**
             * Jitter
             * @default 0.2
             */
            jitter: number;
            /**
             * Maxattempts
             * @default 5
             */
            maxAttempts: number;
            /**
             * Maxdelayms
             * @default 30000
             */
            maxDelayMs: number;
        };
        /** RuntimeAgentSpec */
        RuntimeAgentSpec: {
            budget?: components["schemas"]["BudgetSpec"];
            completion?: components["schemas"]["CompletionSpec"];
            /**
             * Instructions
             * @default
             */
            instructions: string;
            /** Maxturns */
            maxTurns?: number | null;
            /**
             * Preset
             * @default standard_agent
             * @enum {string}
             */
            preset: "standard_agent" | "deep_agent" | "coordinator";
            /** Tools */
            tools?: string[] | null;
        };
        /** RuntimeSpec */
        RuntimeSpec: {
            agent?: components["schemas"]["RuntimeAgentSpec"];
            provider?: components["schemas"]["ProviderSpec"];
        };
        /** SaveBlueprintRequest */
        SaveBlueprintRequest: {
            /** Basedigest */
            baseDigest: string;
            /** Yaml */
            yaml: string;
        };
        /**
         * SemanticDiffEntry
         * @description One deterministic, JSON-pointer-addressed semantic change.
         */
        SemanticDiffEntry: {
            after?: components["schemas"]["JsonValue"] | null;
            before?: components["schemas"]["JsonValue"] | null;
            /**
             * Operation
             * @enum {string}
             */
            operation: "add" | "remove" | "replace";
            /** Path */
            path: string;
        };
        /** ServiceInfo */
        ServiceInfo: {
            /**
             * Apiversion
             * @default v1
             * @constant
             */
            apiVersion: "v1";
            /**
             * Authoringavailable
             * @default false
             */
            authoringAvailable: boolean;
            /**
             * Name
             * @default linch-studio
             * @constant
             */
            name: "linch-studio";
            /**
             * Supportavailable
             * @default false
             */
            supportAvailable: boolean;
        };
        /** SkillSpec */
        SkillSpec: {
            /** Allowedtools */
            allowedTools?: string[];
            /**
             * Description
             * @default
             */
            description: string;
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /** Instructions */
            instructions: string;
        };
        /** StructuredOutputCapabilitySpec */
        StructuredOutputCapabilitySpec: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Finaltoolname */
            finalToolName?: string | null;
            /**
             * Name
             * @default result
             */
            name: string;
            /**
             * Repairretries
             * @default 0
             */
            repairRetries: number;
            /** Schema */
            schema?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Strict
             * @default true
             */
            strict: boolean;
        };
        /** SubagentSpec */
        SubagentSpec: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /** Instructions */
            instructions: string;
            /** Tools */
            tools?: string[];
        };
        /** SupportEvidence */
        SupportEvidence: {
            /** Anchor */
            anchor: string;
            /** Claim */
            claim: string;
            /** Excerpt */
            excerpt?: string | null;
        };
        /** SupportHandoff */
        SupportHandoff: {
            /** Commands */
            commands?: components["schemas"]["SupportRecipeCommand"][];
            /** Environment */
            environment?: string[];
            /** Starthere */
            startHere: string[];
            /** Todos */
            todos?: components["schemas"]["SupportRecipeTodo"][];
        };
        /** SupportImplementationIntent */
        SupportImplementationIntent: {
            /** Capabilities */
            capabilities?: string[];
            /** Constraints */
            constraints?: string[];
            /** Schedule */
            schedule?: string | null;
            /** Summary */
            summary: string;
            /** Workflowshape */
            workflowShape?: string | null;
        };
        /** SupportPipelineIntent */
        SupportPipelineIntent: {
            /** Proposedcomponents */
            proposedComponents?: string[];
            /**
             * Requiresproject
             * @default true
             */
            requiresProject: boolean;
            /** Summary */
            summary: string;
        };
        /** SupportRecipe */
        SupportRecipe: {
            /** Files */
            files: components["schemas"]["SupportRecipeFile"][];
            handoff: components["schemas"]["SupportHandoff"];
            intent: components["schemas"]["SupportImplementationIntent"];
            /** Overview */
            overview: string;
            /** Tests */
            tests?: components["schemas"]["SupportRecipeFile"][];
            /** Title */
            title: string;
        };
        /** SupportRecipeCommand */
        SupportRecipeCommand: {
            /** Command */
            command: string;
            /** Purpose */
            purpose: string;
        };
        /** SupportRecipeFile */
        SupportRecipeFile: {
            /** Content */
            content: string;
            /** Evidence */
            evidence?: string[];
            /** Explanation */
            explanation?: string | null;
            /**
             * Language
             * @enum {string}
             */
            language: "python" | "toml" | "yaml" | "text" | "shell";
            /** Path */
            path: string;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "copied" | "composed" | "skeleton";
        };
        /** SupportRecipeTodo */
        SupportRecipeTodo: {
            /**
             * Blocking
             * @default true
             */
            blocking: boolean;
            /** Description */
            description: string;
            /**
             * Owner
             * @default developer
             * @enum {string}
             */
            owner: "developer" | "host" | "security";
        };
        /** SupportTurnRequest */
        SupportTurnRequest: {
            /** Approvedplandigest */
            approvedPlanDigest?: string | null;
            /** Messages */
            messages: components["schemas"]["TurnMessage"][];
            /**
             * Pipelineconfirmed
             * @default false
             */
            pipelineConfirmed: boolean;
            /** Projectid */
            projectId?: string | null;
            /**
             * Requestedmode
             * @default auto
             * @enum {string}
             */
            requestedMode: "auto" | "documentation" | "implementation" | "pipeline";
            /**
             * Stage
             * @default chat
             * @enum {string}
             */
            stage: "chat" | "build";
        };
        /**
         * SupportTurnResponse
         * @description One global support turn; exactly one matching artifact is populated.
         */
        SupportTurnResponse: {
            /** Answer */
            answer?: string | null;
            /**
             * Coverage
             * @default partial
             * @enum {string}
             */
            coverage: "documented" | "partial" | "not_found";
            /** Evidence */
            evidence?: components["schemas"]["SupportEvidence"][];
            /** Followup */
            followUp?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "answer" | "recipe" | "mode_confirmation" | "questions" | "plan" | "proposal";
            /**
             * Mode
             * @enum {string}
             */
            mode: "documentation" | "implementation" | "pipeline";
            pipelineIntent?: components["schemas"]["SupportPipelineIntent"] | null;
            /** Plan */
            plan?: string | null;
            /** Plandigest */
            planDigest?: string | null;
            proposal?: components["schemas"]["ProposalResponse"] | null;
            /** Questions */
            questions?: components["schemas"]["TurnQuestion"][];
            recipe?: components["schemas"]["SupportRecipe"] | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["TurnToolCall"][];
        };
        /** TargetSpec */
        TargetSpec: {
            /**
             * Linch
             * @default >=1.1,<2
             */
            linch: string;
            /**
             * Python
             * @default >=3.10
             */
            python: string;
        };
        /** TextContainsVerifierSpec */
        TextContainsVerifierSpec: {
            /** Feedback */
            feedback?: string | null;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text_contains";
            /** Text */
            text: string;
        };
        /** ThinkingSpec */
        ThinkingSpec: {
            /** Budgettokens */
            budgetTokens?: number | null;
            /** Effort */
            effort?: ("low" | "medium" | "high" | "xhigh" | "max") | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /** ToolPermissionRuleSpec */
        ToolPermissionRuleSpec: {
            /** Argument */
            argument?: string | null;
            /**
             * Decision
             * @default ask
             * @enum {string}
             */
            decision: "allow" | "deny" | "ask" | "passthrough";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "tool";
            /** Tool */
            tool: string;
        };
        /** TruncationRecoverySpec */
        TruncationRecoverySpec: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /** Feedback */
            feedback?: string | null;
            /**
             * Maxattempts
             * @default 1
             */
            maxAttempts: number;
        };
        /** TurnMessage */
        TurnMessage: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** TurnQuestion */
        TurnQuestion: {
            /** Options */
            options: string[];
            /** Question */
            question: string;
        };
        /** TurnRequest */
        TurnRequest: {
            /** Messages */
            messages: components["schemas"]["TurnMessage"][];
            /**
             * Stage
             * @default chat
             * @enum {string}
             */
            stage: "chat" | "build";
        };
        /** TurnResponse */
        TurnResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "questions" | "plan" | "proposal";
            /** Plan */
            plan?: string | null;
            /** Plannote */
            planNote?: string | null;
            proposal?: components["schemas"]["ProposalResponse"] | null;
            /** Questions */
            questions?: components["schemas"]["TurnQuestion"][];
            /** Thinking */
            thinking?: string | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["TurnToolCall"][];
        };
        /**
         * TurnToolCall
         * @description One read-only knowledge-tool call, for the chat UI's compact tool-call row.
         */
        TurnToolCall: {
            /** Detail */
            detail?: string | null;
            /**
             * Durationms
             * @default 0
             */
            durationMs: number;
            /**
             * Iserror
             * @default false
             */
            isError: boolean;
            /** Resultsummary */
            resultSummary?: string | null;
            /** Summary */
            summary: string;
            /** Toolname */
            toolName: string;
            /** Tooluseid */
            toolUseId: string;
        };
        /** ValidateBlueprintRequest */
        ValidateBlueprintRequest: {
            /** Yaml */
            yaml: string;
        };
        /** ValidationResponse */
        ValidationResponse: {
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Digest */
            digest?: string | null;
            /** Exportready */
            exportReady: boolean;
            /** Structurallyvalid */
            structurallyValid: boolean;
        };
        /** WebhookTriggerSpec */
        WebhookTriggerSpec: {
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "webhook";
            /** Signingsecretenv */
            signingSecretEnv?: string | null;
        };
        /** WorkflowRunRoutineSpec */
        WorkflowRunRoutineSpec: {
            budget?: components["schemas"]["BudgetSpec"];
            /** Displayname */
            displayName: string;
            /** Donewhen */
            doneWhen?: (components["schemas"]["TextContainsVerifierSpec"] | components["schemas"]["JsonSchemaVerifierSpec"] | components["schemas"]["CustomTodoVerifierSpec"]) | null;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "workflow_run";
            /** Maxturns */
            maxTurns?: number | null;
            /** Target */
            target: string;
            /** Triggers */
            triggers?: string[];
            /** Verify */
            verify?: (components["schemas"]["TextContainsVerifierSpec"] | components["schemas"]["JsonSchemaVerifierSpec"] | components["schemas"]["CustomTodoVerifierSpec"]) | null;
        };
        /** WorkflowSpec */
        WorkflowSpec: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Displayname */
            displayName: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @default directed
             * @constant
             */
            kind: "directed";
            /**
             * Maxconcurrency
             * @default 4
             */
            maxConcurrency: number;
            /** Nodes */
            nodes?: (components["schemas"]["AgentCallNodeSpec"] | components["schemas"]["DirectToolNodeSpec"])[];
            /** Output */
            output?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    service_info_api_v1_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    capability_catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityCatalogResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    open_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_authoring_turn_api_v1_projects__project_id__authoring_turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    stream_authoring_turn_api_v1_projects__project_id__authoring_turns_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Server-sent events: `thinking` deltas while the model reasons, `tool_call_start`/`tool_call_end` around each knowledge-tool call, then exactly one terminal `turn` (a TurnResponse) or `error` event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    save_blueprint_api_v1_projects__project_id__blueprint_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveBlueprintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    write_export_api_v1_projects__project_id__export_directory_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectoryExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryExportResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    preview_export_api_v1_projects__project_id__export_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportPreviewResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    download_export_api_v1_projects__project_id__export_zip_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    load_layout_api_v1_projects__project_id__layout_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    save_layout_api_v1_projects__project_id__layout_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayoutDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayoutResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_proposals_api_v1_projects__project_id__proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalListResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_proposal_api_v1_projects__project_id__proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_proposal_api_v1_projects__project_id__proposals__proposal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    accept_proposal_api_v1_projects__project_id__proposals__proposal_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    reject_proposal_api_v1_projects__project_id__proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    validate_project_api_v1_projects__project_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    blueprint_schema_api_v1_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_support_turn_api_v1_support_turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupportTurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportTurnResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    stream_support_turn_api_v1_support_turns_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupportTurnRequest"];
            };
        };
        responses: {
            /** @description One terminal support `turn` or `error` event; reasoning is never streamed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    validate_buffer_api_v1_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateBlueprintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
