"""Public API for agent_kit."""

from .agent import Agent, AgentOptions
from .config import FeatureFlags, SystemPromptConfig
from .context_hooks import ContextInjector, TurnContext, prune_tagged
from .errors import (
    AbortError,
    AgentKitError,
    AuthError,
    ConfigError,
    ContextLengthError,
    PermissionDeniedError,
    ProviderError,
    RateLimitError,
    SkillError,
    ToolExecutionError,
)
from .events import (
    AssistantEvent,
    CompactionEvent,
    ErrorEvent,
    Event,
    PartialAssistantEvent,
    PermissionRequestEvent,
    ResultEvent,
    SkillCompletedEvent,
    SkillInvokedEvent,
    SkillsLoadedEvent,
    SubagentEvent,
    SystemEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
    UsageEvent,
    UserEvent,
    is_subagent_event,
)
from .mcp import (
    McpHttpServerConfig,
    McpServerConfig,
    McpStdioServerConfig,
    connect_mcp_servers,
)
from .openai_responses import OpenAIOptions, OpenAIReasoning
from .providers import (
    AnthropicProvider,
    AnthropicProviderOptions,
    BaseProvider,
    OpenAIChatCompletionsProvider,
    OpenAIChatProviderOptions,
    OpenAIResponsesProvider,
    OpenAIResponsesProviderOptions,
)
from .session import RunOptions, Session
from .tools import (
    FileReadTracker,
    Tool,
    ToolContext,
    ToolRegistry,
    ToolResult,
    default_tools,
)
from .tools.registry import empty_tools, tools_from_defaults
from .types import (
    ContentBlock,
    ImageBlock,
    Message,
    ModelId,
    OutputSchema,
    PermissionMode,
    StopReason,
    TextBlock,
    ThinkingBlock,
    ToolChoice,
    ToolResultBlock,
    ToolUseBlock,
    Usage,
)

defaultTools = default_tools

__all__ = [
    "AbortError",
    "Agent",
    "AgentKitError",
    "AgentOptions",
    "ContextInjector",
    "TurnContext",
    "prune_tagged",
    "FeatureFlags",
    "SystemPromptConfig",
    "OutputSchema",
    "ToolChoice",
    "empty_tools",
    "tools_from_defaults",
    "AssistantEvent",
    "CompactionEvent",
    "ContentBlock",
    "ErrorEvent",
    "Event",
    "ImageBlock",
    "AuthError",
    "ConfigError",
    "ContextLengthError",
    "FileReadTracker",
    "McpHttpServerConfig",
    "McpServerConfig",
    "McpStdioServerConfig",
    "Message",
    "ModelId",
    "OpenAIOptions",
    "OpenAIReasoning",
    "PartialAssistantEvent",
    "PermissionMode",
    "PermissionDeniedError",
    "PermissionRequestEvent",
    "ProviderError",
    "RateLimitError",
    "ResultEvent",
    "RunOptions",
    "SkillCompletedEvent",
    "SkillError",
    "ThinkingBlock",
    "SkillInvokedEvent",
    "SkillsLoadedEvent",
    "StopReason",
    "SubagentEvent",
    "SystemEvent",
    "Session",
    "TextBlock",
    "Tool",
    "ToolCallEndEvent",
    "ToolCallStartEvent",
    "ToolContext",
    "ToolExecutionError",
    "ToolRegistry",
    "ToolResultBlock",
    "ToolResult",
    "ToolUseBlock",
    "Usage",
    "UsageEvent",
    "UserEvent",
    "AnthropicProvider",
    "AnthropicProviderOptions",
    "BaseProvider",
    "OpenAIChatCompletionsProvider",
    "OpenAIChatProviderOptions",
    "OpenAIResponsesProvider",
    "OpenAIResponsesProviderOptions",
    "connect_mcp_servers",
    "defaultTools",
    "default_tools",
    "is_subagent_event",
]
