"""Optional, stateless AI proposal authoring for Linch Studio."""

from .config import SUPPORTED_AUTHORING_PROVIDERS, AuthoringConfig
from .diff import semantic_diff
from .errors import (
    AuthoringConfigurationError,
    AuthoringError,
    InvalidInstructionError,
    MalformedProposalError,
    ManualOnlyFieldError,
    ProposalBudgetError,
    ProposalGenerationError,
    ProposalNotFoundError,
    ProposalStateError,
    ProposalTimeoutError,
    SemanticProposalError,
    StaleProposalError,
)
from .guards import manual_only_diagnostics
from .knowledge import KnowledgeBase
from .layout import (
    HORIZONTAL_GAP,
    VERTICAL_GAP,
    deterministic_layout_for_new_nodes,
    workflow_node_key,
)
from .models import (
    MAX_MESSAGE_CHARS,
    MAX_TOOL_DETAIL_CHARS,
    MAX_TOOL_SUMMARY_CHARS,
    MAX_TRANSCRIPT_CHARS,
    MAX_TRANSCRIPT_MESSAGES,
    AuthoringMessage,
    AuthoringQuestion,
    AuthoringStage,
    AuthoringTurn,
    AuthoringTurnOutput,
    DiffOperation,
    Proposal,
    ProposalState,
    ProposalTelemetry,
    SemanticDiffEntry,
    TelemetryStatus,
    ToolCallPhase,
    ToolCallRecord,
    ToolCallUpdate,
)
from .providers import create_authoring_provider
from .repository import InMemoryProposalRepository
from .service import (
    AUTHORING_SYSTEM_PROMPT,
    MAX_INSTRUCTION_CHARS,
    AgentBuildRequest,
    AgentFactory,
    LinchProposalService,
    ProviderFactory,
    build_conversation_prompt,
    build_proposal_prompt,
    create_authoring_agent,
)
from .tools import AuthoringDeps, ReadSectionTool, SearchDocsTool

__all__ = [
    "AUTHORING_SYSTEM_PROMPT",
    "HORIZONTAL_GAP",
    "MAX_INSTRUCTION_CHARS",
    "MAX_MESSAGE_CHARS",
    "MAX_TOOL_DETAIL_CHARS",
    "MAX_TOOL_SUMMARY_CHARS",
    "MAX_TRANSCRIPT_CHARS",
    "MAX_TRANSCRIPT_MESSAGES",
    "SUPPORTED_AUTHORING_PROVIDERS",
    "VERTICAL_GAP",
    "AgentBuildRequest",
    "AgentFactory",
    "AuthoringConfig",
    "AuthoringDeps",
    "AuthoringMessage",
    "AuthoringQuestion",
    "AuthoringStage",
    "AuthoringTurn",
    "AuthoringTurnOutput",
    "AuthoringConfigurationError",
    "AuthoringError",
    "DiffOperation",
    "InMemoryProposalRepository",
    "InvalidInstructionError",
    "KnowledgeBase",
    "LinchProposalService",
    "MalformedProposalError",
    "ManualOnlyFieldError",
    "Proposal",
    "ProposalBudgetError",
    "ProposalGenerationError",
    "ProposalNotFoundError",
    "ProposalState",
    "ProposalStateError",
    "ProposalTelemetry",
    "ProposalTimeoutError",
    "ProviderFactory",
    "ReadSectionTool",
    "SearchDocsTool",
    "SemanticDiffEntry",
    "SemanticProposalError",
    "StaleProposalError",
    "TelemetryStatus",
    "ToolCallPhase",
    "ToolCallRecord",
    "ToolCallUpdate",
    "build_conversation_prompt",
    "build_proposal_prompt",
    "create_authoring_agent",
    "create_authoring_provider",
    "deterministic_layout_for_new_nodes",
    "manual_only_diagnostics",
    "semantic_diff",
    "workflow_node_key",
]
