import type { NodeKind } from "./graph";

export type FieldType = "text" | "number" | "select" | "json";
export type InspectorSection =
  | "Capabilities"
  | "Quality"
  | "Safety"
  | "Lifecycle"
  | "Provider"
  | "Memory"
  | "MCP";

export interface FieldSpec {
  /** Path relative to the node's own strict Blueprint pointer. */
  key: string;
  label: string;
  section: InspectorSection;
  tier: "basic" | "advanced";
  type: FieldType;
  required?: boolean;
  env?: boolean;
  options?: string[];
  desc?: string;
  /** Variant guard for fields that exist only on one discriminated-union member. */
  when?: { key: string; value: string };
}

export const FIELDS: Record<NodeKind, FieldSpec[]> = {
  runtime_agent: [
    {
      key: "preset",
      label: "PRESET",
      section: "Capabilities",
      tier: "basic",
      type: "select",
      options: ["standard_agent", "deep_agent", "coordinator"],
      desc: "deep agents are model-directed; this does not create control-flow edges",
    },
    {
      key: "instructions",
      label: "INSTRUCTIONS",
      section: "Capabilities",
      tier: "basic",
      type: "text",
    },
    {
      key: "tools",
      label: "TOOL ALLOWLIST",
      section: "Capabilities",
      tier: "advanced",
      type: "json",
      desc: "null/omitted means every declared tool; a list is an explicit runtime allowlist",
    },
    {
      key: "completion/mode",
      label: "COMPLETION",
      section: "Quality",
      tier: "basic",
      type: "select",
      options: ["agent_judged", "verifier_gated"],
    },
    {
      key: "completion/maxRetries",
      label: "VERIFIER RETRIES",
      section: "Quality",
      tier: "advanced",
      type: "number",
      when: { key: "completion/mode", value: "verifier_gated" },
    },
    {
      key: "completion/verifiers",
      label: "VERIFIERS",
      section: "Quality",
      tier: "advanced",
      type: "json",
      desc: "text_contains and json_schema run; custom_todo rejects until implemented",
      when: { key: "completion/mode", value: "verifier_gated" },
    },
    {
      key: "maxTurns",
      label: "TURN LIMIT",
      section: "Safety",
      tier: "advanced",
      type: "number",
      desc: "shared ceiling inherited by subagents",
    },
    {
      key: "budget/maxTokens",
      label: "TOKEN BUDGET",
      section: "Safety",
      tier: "advanced",
      type: "number",
      desc: "shared by the entire agent tree",
    },
    {
      key: "budget/maxCostUsd",
      label: "COST BUDGET (USD)",
      section: "Safety",
      tier: "advanced",
      type: "number",
    },
  ],
  subagent: [
    {
      key: "id",
      label: "NAME",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "displayName",
      label: "DISPLAY NAME",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "instructions",
      label: "INSTRUCTIONS",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "tools",
      label: "TOOL ALLOWLIST",
      section: "Capabilities",
      tier: "advanced",
      type: "json",
      desc: "prefer magnetic Tool attachments; this field is the same Blueprint allowlist",
    },
  ],
  directed_workflow: [
    {
      key: "id",
      label: "NAME",
      section: "Lifecycle",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "displayName",
      label: "DISPLAY NAME",
      section: "Lifecycle",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "output",
      label: "OUTPUT STEP",
      section: "Quality",
      tier: "basic",
      type: "text",
      desc: "must reference one terminal step; newly added steps become terminal automatically",
    },
    {
      key: "maxConcurrency",
      label: "MAX CONCURRENCY",
      section: "Safety",
      tier: "advanced",
      type: "number",
    },
  ],
  workflow_step: [
    {
      key: "id",
      label: "NAME",
      section: "Lifecycle",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "label",
      label: "LABEL",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "prompt",
      label: "PROMPT",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "subagent",
      label: "SUBAGENT",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      desc: "prefer the subagent attachment connector; at most one binding",
    },
    {
      key: "tools",
      label: "TOOL ALLOWLIST",
      section: "Capabilities",
      tier: "advanced",
      type: "json",
      desc: "prefer magnetic Tool attachments; filters tools for this invocation",
    },
    {
      key: "dependsOn",
      label: "A2A DEPENDENCIES",
      section: "Lifecycle",
      tier: "advanced",
      type: "json",
      desc: "prefer workflow handles; dependencies must stay acyclic and in this workflow",
    },
    {
      key: "phase",
      label: "PHASE",
      section: "Lifecycle",
      tier: "advanced",
      type: "text",
    },
  ],
  routine: [
    {
      key: "id",
      label: "NAME",
      section: "Lifecycle",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "displayName",
      label: "DISPLAY NAME",
      section: "Lifecycle",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "target",
      label: "TARGET",
      section: "Lifecycle",
      tier: "basic",
      type: "text",
      required: true,
      desc: "agent_tick targets runtime_agent; workflow_run targets a directed workflow id",
    },
    {
      key: "triggers",
      label: "TRIGGERS",
      section: "Lifecycle",
      tier: "advanced",
      type: "json",
      desc: "prefer magnetic Trigger attachments in this Routine scope",
    },
    {
      key: "charter",
      label: "CHARTER",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      when: { key: "kind", value: "agent_tick" },
    },
    {
      key: "prompt",
      label: "PROMPT",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      when: { key: "kind", value: "agent_tick" },
    },
    {
      key: "maxTurns",
      label: "TURN LIMIT",
      section: "Safety",
      tier: "advanced",
      type: "number",
    },
    {
      key: "budget/maxTokens",
      label: "TOKEN BUDGET",
      section: "Safety",
      tier: "advanced",
      type: "number",
    },
    {
      key: "verify",
      label: "INVOCATION VERIFIER",
      section: "Quality",
      tier: "advanced",
      type: "json",
    },
    {
      key: "doneWhen",
      label: "DONE WHEN",
      section: "Lifecycle",
      tier: "advanced",
      type: "json",
      desc: "reports done; it does not cancel a host cron schedule",
    },
  ],
  trigger: [
    {
      key: "id",
      label: "NAME",
      section: "Lifecycle",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "displayName",
      label: "DISPLAY NAME",
      section: "Lifecycle",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "cron",
      label: "CRON",
      section: "Lifecycle",
      tier: "basic",
      type: "text",
      when: { key: "kind", value: "cron" },
    },
    {
      key: "timezone",
      label: "TIMEZONE",
      section: "Lifecycle",
      tier: "advanced",
      type: "text",
      when: { key: "kind", value: "cron" },
    },
    {
      key: "provider",
      label: "CI PROVIDER",
      section: "Lifecycle",
      tier: "basic",
      type: "select",
      options: ["generic", "github_actions"],
      when: { key: "kind", value: "ci" },
    },
    {
      key: "signingSecretEnv",
      label: "SIGNING SECRET ENV",
      section: "Safety",
      tier: "basic",
      type: "text",
      env: true,
      when: { key: "kind", value: "webhook" },
    },
  ],
  tool: [
    {
      key: "id",
      label: "NAME",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "displayName",
      label: "DISPLAY NAME",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "description",
      label: "DESCRIPTION",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "timeoutMs",
      label: "TIMEOUT (ms)",
      section: "Safety",
      tier: "advanced",
      type: "number",
    },
    {
      key: "retryable",
      label: "RETRYABLE",
      section: "Safety",
      tier: "advanced",
      type: "select",
      options: ["true", "false"],
    },
  ],
  skill: [
    {
      key: "id",
      label: "NAME",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "displayName",
      label: "DISPLAY NAME",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "instructions",
      label: "INSTRUCTIONS",
      section: "Capabilities",
      tier: "basic",
      type: "text",
      required: true,
    },
    {
      key: "allowedTools",
      label: "ALLOWED TOOLS",
      section: "Capabilities",
      tier: "advanced",
      type: "json",
      desc: "prefer magnetic Tool attachments; this list is emitted into skill frontmatter",
    },
  ],
};

/**
 * Runtime configuration that has no card on any canvas. Provider, memory, and MCP
 * are rails: they change how the exported project is wired, never the graph. Keys
 * are relative to `/spec`, and every one of them is a real strict-model field.
 */
export const PROJECT_FIELDS: FieldSpec[] = [
  {
    key: "runtime/provider/kind",
    label: "PROVIDER",
    section: "Provider",
    tier: "basic",
    type: "select",
    options: [
      "openai_responses",
      "openai_chat",
      "anthropic",
      "gemini",
      "llama_cpp",
      "vllm",
      "sglang",
      "custom",
    ],
    desc: "selects the generated provider wiring; no key is ever stored in the Blueprint",
  },
  {
    key: "runtime/provider/model",
    label: "MODEL",
    section: "Provider",
    tier: "basic",
    type: "text",
  },
  {
    key: "runtime/provider/apiKeyEnv",
    label: "API KEY ENV",
    section: "Provider",
    tier: "basic",
    type: "text",
    env: true,
    desc: "the environment variable name to read at runtime, e.g. OPENAI_API_KEY",
  },
  {
    key: "runtime/provider/baseUrlEnv",
    label: "BASE URL ENV",
    section: "Provider",
    tier: "basic",
    type: "text",
    env: true,
    desc: "env var holding a self-hosted or proxy endpoint, e.g. OPENAI_BASE_URL",
  },
  {
    key: "capabilities/memory/backend",
    label: "MEMORY BACKEND",
    section: "Memory",
    tier: "basic",
    type: "select",
    options: [
      "none",
      "in_memory",
      "sqlite",
      "postgres_keyword",
      "tiered",
      "faiss",
      "pgvector",
      "qdrant",
      "custom",
    ],
    desc: "a store, not a Tool — it never becomes a card or an edge",
  },
  {
    key: "capabilities/memory/namespace",
    label: "NAMESPACE",
    section: "Memory",
    tier: "basic",
    type: "text",
  },
  {
    key: "capabilities/memory/dsnEnv",
    label: "DSN ENV",
    section: "Memory",
    tier: "basic",
    type: "text",
    env: true,
    desc: "env var holding the connection string for a sqlite/postgres/vector backend",
  },
  {
    key: "capabilities/context/memoryRecall",
    label: "RECALL INJECTION",
    section: "Memory",
    tier: "basic",
    type: "select",
    options: ["true", "false"],
    desc: "injects recalled memory into context through a hook, not a tool call",
  },
  {
    key: "capabilities/memory/searchTool",
    label: "SEARCH TOOL",
    section: "Memory",
    tier: "basic",
    type: "select",
    options: ["true", "false"],
    desc: "generates a memory-search tool the agent may call",
  },
  {
    key: "capabilities/memory/upsertTool",
    label: "UPSERT TOOL",
    section: "Memory",
    tier: "basic",
    type: "select",
    options: ["true", "false"],
    desc: "generates a memory-write tool the agent may call",
  },
  {
    key: "capabilities/memory/extractionHook",
    label: "EXTRACTION HOOK [td]",
    section: "Memory",
    tier: "basic",
    type: "select",
    options: ["true", "false"],
    desc: "skeleton/todo: exports a seam and a blocking TODO, not working extraction",
  },
  {
    key: "capabilities/extensions/mcpServers",
    label: "MCP SERVERS",
    section: "MCP",
    tier: "basic",
    type: "json",
    desc: 'a server supplies tools/resources; it is not a Tool card. http: [{"kind":"http","id":"docs","url":"https://…","tokenEnv":"MCP_TOKEN"}]. stdio servers take a local command/args and are yours to write by hand.',
  },
  {
    key: "capabilities/extensions/liveMcpDiscovery",
    label: "LIVE DISCOVERY",
    section: "MCP",
    tier: "basic",
    type: "select",
    options: ["true", "false"],
    desc: "lists server tools at runtime instead of pinning them at export",
  },
];
